package com.itsol.smartweb32.model;
// Generated Mar 10, 2019 9:23:25 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Candidate generated by hbm2java
 */
@Entity
@Table(name = "candidate", catalog = "smart_web_3")
public class Candidate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private Job job;
	private String firstname;
	private String lastname;
	private String birthday;
	private String mobile;
	private String content;
	private String cvfile;

	public Candidate() {
	}

	public Candidate(Job job) {
		this.job = job;
	}

	public Candidate(Job job, String firstname, String lastname, String birthday, String mobile, String content,
			String cvfile) {
		this.job = job;
		this.firstname = firstname;
		this.lastname = lastname;
		this.birthday = birthday;
		this.mobile = mobile;
		this.content = content;
		this.cvfile = cvfile;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "job_id", nullable = false)
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	@Column(name = "firstname", length = 40)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 40)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "birthday", length = 20)
	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	@Column(name = "mobile", length = 11)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "cvfile", length = 65535)
	public String getCvfile() {
		return this.cvfile;
	}

	public void setCvfile(String cvfile) {
		this.cvfile = cvfile;
	}

}
