package com.itsol.smartweb32.model;
// Generated Mar 10, 2019 9:23:25 PM by Hibernate Tools 3.5.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.NaturalId;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "smart_web_3", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Roles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private RoleName name;
	//private Set<Users> userses = new HashSet<Users>(0);

	public Roles() {
	}

	public Roles(RoleName name) {
        this.name = name;
    }


//	public Roles(RoleName name, Set<Users> userses) {
//		this.name = name;
//		this.userses = userses;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

//	@Column(name = "name", unique = true, nullable = false, length = 20)
	@Enumerated(EnumType.STRING)
    @NaturalId
	public RoleName getName() {
        return name;
    }

    public void setName(RoleName name) {
        this.name = name;
    }

//	@ManyToMany(fetch = FetchType.LAZY)
//	@JoinTable(name = "user_roles", catalog = "smart_web_3", joinColumns = {
//			@JoinColumn(name = "role_id", nullable = false, updatable = false) }, inverseJoinColumns = {
//					@JoinColumn(name = "user_id", nullable = false, updatable = false) })
//	public Set<Users> getUserses() {
//		return this.userses;
//	}
//
//	public void setUserses(Set<Users> userses) {
//		this.userses = userses;
//	}

}
